INSERT INTO popular_instruments (
    id,
    instrument_id,
    category,
    rank,
    active,
    created_at,
    created_by
)
SELECT
    gen_random_uuid(),
    i.id,
    'TECH',
    data.rank,
    true,
    NOW(),
    'SYSTEM'
FROM instruments i
JOIN (
    VALUES
        ('AAPL', 1),
        ('MSFT', 2),
        ('NVDA', 3),
        ('GOOGL', 4),
        ('META', 5),
        ('AMZN', 6),
        ('AVGO', 7),
        ('TSLA', 8),
        ('AMD', 9),
        ('NFLX', 10),
        ('ORCL', 11),
        ('CRM', 12),
        ('ADBE', 13),
        ('CSCO', 14),
        ('INTC', 15),
        ('QCOM', 16),
        ('IBM', 17),
        ('TXN', 18),
        ('AMAT', 19),
        ('MU', 20),
        ('NOW', 21),
        ('PANW', 22),
        ('SNOW', 23),
        ('PLTR', 24),
        ('SHOP', 25),
        ('CRWD', 26),
        ('ADI', 27),
        ('KLAC', 28),
        ('LRCX', 29),
        ('ANET', 30),
        ('INTU', 31),
        ('UBER', 32),
        ('SQ', 33),
        ('PYPL', 34),
        ('ZM', 35),
        ('DOCU', 36),
        ('TEAM', 37),
        ('DDOG', 38),
        ('MDB', 39),
        ('NET', 40),
        ('ZS', 41),
        ('OKTA', 42),
        ('WDAY', 43),
        ('FSLR', 44),
        ('DELL', 45),
        ('HPQ', 46),
        ('ARM', 47),
        ('RBLX', 48),
        ('U', 49),
        ('ESTC', 50)
) AS data(symbol, rank)
ON i.symbol = data.symbol;