INSERT INTO popular_instruments (
    id,
    instrument_id,
    category,
    rank,
    active,
    created_at,
    created_by
)
SELECT
    gen_random_uuid(),
    i.id,
    'BANKING',
    data.rank,
    true,
    NOW(),
    'SYSTEM'
FROM instruments i
JOIN (
    VALUES
        ('JPM', 1),
        ('BAC', 2),
        ('WFC', 3),
        ('C', 4),
        ('GS', 5),
        ('MS', 6),
        ('AXP', 7),
        ('V', 8),
        ('MA', 9),
        ('BLK', 10),
        ('SCHW', 11),
        ('BK', 12),
        ('USB', 13),
        ('PNC', 14),
        ('TFC', 15),
        ('COF', 16),
        ('MSCI', 17),
        ('SPGI', 18),
        ('ICE', 19),
        ('CME', 20),
        ('MCO', 21),
        ('CB', 22),
        ('AIG', 23),
        ('PGR', 24),
        ('MET', 25),
        ('TRV', 26),
        ('ALL', 27),
        ('PRU', 28),
        ('AON', 29),
        ('MMC', 30),
        ('DFS', 31),
        ('SYF', 32),
        ('FITB', 33),
        ('RF', 34),
        ('HBAN', 35),
        ('KEY', 36),
        ('CFG', 37),
        ('MTB', 38),
        ('FRC', 39),
        ('NTRS', 40),
        ('STT', 41),
        ('BRO', 42),
        ('BEN', 43),
        ('IVZ', 44),
        ('TROW', 45),
        ('CINF', 46),
        ('AJG', 47),
        ('WRB', 48),
        ('PFG', 49),
        ('AMP', 50)
) AS data(symbol, rank)
ON i.symbol = data.symbol;