INSERT INTO popular_instruments (
    id,
    instrument_id,
    category,
    rank,
    active,
    created_at,
    created_by
)
SELECT
    gen_random_uuid(),
    i.id,
    'HEALTHCARE',
    data.rank,
    true,
    NOW(),
    'SYSTEM'
FROM instruments i
JOIN (
    VALUES
        ('UNH', 1),
        ('JNJ', 2),
        ('LLY', 3),
        ('ABBV', 4),
        ('MRK', 5),
        ('PFE', 6),
        ('TMO', 7),
        ('ABT', 8),
        ('DHR', 9),
        ('BMY', 10),
        ('AMGN', 11),
        ('GILD', 12),
        ('MDT', 13),
        ('CVS', 14),
        ('CI', 15),
        ('HUM', 16),
        ('ISRG', 17),
        ('SYK', 18),
        ('BSX', 19),
        ('VRTX', 20),
        ('REGN', 21),
        ('ZTS', 22),
        ('BDX', 23),
        ('EW', 24),
        ('DXCM', 25),
        ('MRNA', 26),
        ('BIIB', 27),
        ('ILMN', 28),
        ('IQV', 29),
        ('HCA', 30),
        ('CAH', 31),
        ('MCK', 32),
        ('BAX', 33),
        ('LH', 34),
        ('DGX', 35),
        ('IDXX', 36),
        ('RMD', 37),
        ('HOLX', 38),
        ('ALGN', 39),
        ('COO', 40),
        ('TECH', 41),
        ('WAT', 42),
        ('STE', 43),
        ('PODD', 44),
        ('RVTY', 45),
        ('MOH', 46),
        ('UHS', 47),
        ('ELV', 48),
        ('COR', 49),
        ('GEHC', 50)
) AS data(symbol, rank)
ON i.symbol = data.symbol;