INSERT INTO popular_instruments (
    id,
    instrument_id,
    category,
    rank,
    active,
    created_at,
    created_by
)
SELECT
    gen_random_uuid(),
    i.id,
    'ENERGY',
    data.rank,
    true,
    NOW(),
    'SYSTEM'
FROM instruments i
JOIN (
    VALUES
        ('XOM', 1),
        ('CVX', 2),
        ('COP', 3),
        ('SLB', 4),
        ('EOG', 5),
        ('MPC', 6),
        ('PSX', 7),
        ('VLO', 8),
        ('OXY', 9),
        ('KMI', 10),
        ('WMB', 11),
        ('EPD', 12),
        ('ET', 13),
        ('HAL', 14),
        ('BKR', 15),
        ('DVN', 16),
        ('FANG', 17),
        ('CTRA', 18),
        ('APA', 19),
        ('MRO', 20),
        ('PXD', 21),
        ('HES', 22),
        ('EQT', 23),
        ('TRGP', 24),
        ('LNG', 25),
        ('NEE', 26),
        ('DUK', 27),
        ('SO', 28),
        ('D', 29),
        ('AEP', 30),
        ('EXC', 31),
        ('SRE', 32),
        ('PEG', 33),
        ('PCG', 34),
        ('XEL', 35),
        ('ED', 36),
        ('WEC', 37),
        ('ES', 38),
        ('FE', 39),
        ('AEE', 40),
        ('FSLR', 41),
        ('ENPH', 42),
        ('SEDG', 43),
        ('RUN', 44),
        ('BE', 45),
        ('PLUG', 46),
        ('AES', 47),
        ('ORA', 48),
        ('CWEN', 49),
        ('NRG', 50)
) AS data(symbol, rank)
ON i.symbol = data.symbol;