INSERT INTO popular_instruments (
    id,
    instrument_id,
    category,
    rank,
    active,
    created_at,
    created_by
)
SELECT
    gen_random_uuid(),   -- or uuid_generate_v4()
    i.id,
    'TOP_50',
    data.rank,
    true,
    NOW(),
    'SYSTEM'
FROM instruments i
JOIN (
    VALUES
        ('AAPL', 1),
        ('MSFT', 2),
        ('NVDA', 3),
        ('AMZN', 4),
        ('GOOGL', 5),
        ('META', 6),
        ('TSLA', 7),
        ('BRK.B', 8),
        ('UNH', 9),
        ('JNJ', 10),
        ('XOM', 11),
        ('JPM', 12),
        ('V', 13),
        ('PG', 14),
        ('MA', 15),
        ('HD', 16),
        ('CVX', 17),
        ('ABBV', 18),
        ('MRK', 19),
        ('PEP', 20),
        ('KO', 21),
        ('AVGO', 22),
        ('COST', 23),
        ('ADBE', 24),
        ('WMT', 25),
        ('MCD', 26),
        ('CSCO', 27),
        ('CRM', 28),
        ('ACN', 29),
        ('TMO', 30),
        ('LIN', 31),
        ('NFLX', 32),
        ('DHR', 33),
        ('ABT', 34),
        ('ORCL', 35),
        ('TXN', 36),
        ('NEE', 37),
        ('AMD', 38),
        ('INTC', 39),
        ('QCOM', 40),
        ('HON', 41),
        ('UNP', 42),
        ('IBM', 43),
        ('LOW', 44),
        ('UPS', 45),
        ('PM', 46),
        ('RTX', 47),
        ('SPGI', 48),
        ('AMAT', 49),
        ('CAT', 50)
) AS data(symbol, rank)
ON i.symbol = data.symbol;