spring:
  application:
    name: stock-pilot

  datasource:
    url: jdbc:postgresql://localhost:5433/stock_pilot?options=-c%20TimeZone=Asia/Kolkata
    username: stock_user
    password: stock_pass

  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 500
        time_zone: Asia/Kolkata
      order_insert: true
      order_update: true
    show-sql: true


  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

jwt:
  secret:
    access: ${ACCESS_SECRET}
    refresh: ${REFRESH_SECRET}

  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}

finnhub:
  base-url: https://finnhub.io/api/v1
  api-key: ${FINNHUB_API_KEY}

