spring.application.name=stock-pilot

spring.datasource.url=jdbc:postgresql://localhost:5432/stock_pilot_db
spring.datasource.username=postgres
spring.datasource.password=King@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true